import { NextResponse } from 'next/server'
import { getSessions, readStatsCache } from '@/lib/claude-reader'
import { estimateCostFromUsage } from '@/lib/pricing'
import { blendedEnergyFactors, impactFromBlended, EQUIVALENCES } from '@/lib/impact'
import { projectDisplayName, isAutoGeneratedProject } from '@/lib/decode'
import type { SessionMeta } from '@/types/claude'

export const dynamic = 'force-dynamic'

function computeLastDisconnection(sessions: SessionMeta[]) {
  const activeDates = new Set<string>()
  for (const s of sessions) {
    if (s.start_time) activeDates.add(s.start_time.slice(0, 10))
  }
  const sorted = [...activeDates].sort()
  let last: { from: string; to: string; days: number } | null = null
  for (let i = 1; i < sorted.length; i++) {
    const prev = new Date(sorted[i - 1]!)
    const curr = new Date(sorted[i]!)
    const diffDays = Math.round((curr.getTime() - prev.getTime()) / 86_400_000)
    if (diffDays > 1) {
      const gapFrom = new Date(prev)
      gapFrom.setDate(gapFrom.getDate() + 1)
      const gapTo = new Date(curr)
      gapTo.setDate(gapTo.getDate() - 1)
      last = {
        from: gapFrom.toISOString().slice(0, 10),
        to: gapTo.toISOString().slice(0, 10),
        days: diffDays - 1,
      }
    }
  }
  return last
}

function sessionCost(s: SessionMeta): number {
  return estimateCostFromUsage(s.model ?? 'claude-sonnet-4-6', {
    input_tokens: s.input_tokens ?? 0,
    output_tokens: s.output_tokens ?? 0,
    cache_creation_input_tokens: s.cache_creation_input_tokens ?? 0,
    cache_read_input_tokens: s.cache_read_input_tokens ?? 0,
  })
}

export async function GET() {
  const [stats, allSessions] = await Promise.all([readStatsCache(), getSessions()])

  const now = new Date()
  const weekAgo = new Date(now); weekAgo.setDate(now.getDate() - 7)
  const twoWeeksAgo = new Date(now); twoWeeksAgo.setDate(now.getDate() - 14)

  const weekSessions = allSessions.filter(s => new Date(s.start_time) >= weekAgo)
  const prevWeekSessions = allSessions.filter(
    s => new Date(s.start_time) >= twoWeeksAgo && new Date(s.start_time) < weekAgo
  )

  // Week stats
  const weekMessages = weekSessions.reduce(
    (sum, s) => sum + (s.user_message_count ?? 0) + (s.assistant_message_count ?? 0), 0
  )
  const weekActiveDays = new Set(weekSessions.map(s => s.start_time.slice(0, 10))).size
  const weekCost = weekSessions.reduce((sum, s) => sum + sessionCost(s), 0)
  const prevWeekCost = prevWeekSessions.reduce((sum, s) => sum + sessionCost(s), 0)
  const costDeltaPct = prevWeekCost > 0.001
    ? ((weekCost - prevWeekCost) / prevWeekCost) * 100
    : null

  // Top project this week
  const projectCounts = new Map<string, number>()
  for (const s of weekSessions) {
    const pp = s.project_path ?? ''
    if (isAutoGeneratedProject(pp) || !pp) continue
    projectCounts.set(pp, (projectCounts.get(pp) ?? 0) + 1)
  }
  let topProject: { name: string; sessions: number } | null = null
  let topCount = 0
  for (const [path, count] of projectCounts) {
    if (count > topCount) {
      topCount = count
      topProject = { name: projectDisplayName(path), sessions: count }
    }
  }

  // Cache efficiency (all-time: cacheRead / total input-like)
  let cacheReadTokens = 0
  let totalInputLike = 0
  for (const u of Object.values(stats?.modelUsage ?? {})) {
    cacheReadTokens += u.cacheReadInputTokens ?? 0
    totalInputLike +=
      (u.inputTokens ?? 0) +
      (u.cacheReadInputTokens ?? 0) +
      (u.cacheCreationInputTokens ?? 0)
  }
  const cacheEfficiencyPct = totalInputLike > 0
    ? Math.round((cacheReadTokens / totalInputLike) * 100)
    : 0

  // Last disconnection +24h (all-time)
  const lastDisconnection = computeLastDisconnection(allSessions)

  // CO₂ all-time
  const factors = blendedEnergyFactors(stats?.modelUsage)
  let co2_g = 0
  for (const s of allSessions) {
    const impact = impactFromBlended(
      {
        input: s.input_tokens ?? 0,
        output: s.output_tokens ?? 0,
        cacheRead: s.cache_read_input_tokens ?? 0,
        cacheWrite: s.cache_creation_input_tokens ?? 0,
      },
      factors,
      'us',
    )
    co2_g += impact.co2_g
  }
  const co2CarKm = Math.round(co2_g / EQUIVALENCES.co2.petrol_car_km)

  return NextResponse.json({
    week: {
      sessions: weekSessions.length,
      messages: weekMessages,
      active_days: weekActiveDays,
      cost_usd: weekCost,
      cost_delta_pct: costDeltaPct,
    },
    top_project: topProject,
    cache_efficiency_pct: cacheEfficiencyPct,
    last_disconnection: lastDisconnection,
    co2_all_time_g: co2_g,
    co2_car_km: co2CarKm,
  })
}
