import { NextResponse } from 'next/server'
import { readStatsCache, getSessions } from '@/lib/claude-reader'
import {
  estimateTotalCostFromModel,
  cacheEfficiency,
  blendedPricing,
  PRICING,
} from '@/lib/pricing'
import { projectDisplayName, isAutoGeneratedProject } from '@/lib/decode'
import type { CostAnalytics, ModelCostBreakdown, DailyCost, ProjectCost } from '@/types/claude'

export const dynamic = 'force-dynamic'

export async function GET() {
  const [stats, sessions] = await Promise.all([readStatsCache(), getSessions()])

  if (!stats) {
    return NextResponse.json({ error: 'stats-cache.json not found' }, { status: 404 })
  }

  // Model mix comes from stats.modelUsage (snapshot, possibly stale), session
  // volumes come from the live on-disk sessions. Blended pricing weights the
  // $-per-token-type by the user's real Opus/Sonnet/Haiku ratios so that
  // applying it to session tokens gives a realistic $ total.
  const blended = blendedPricing(stats.modelUsage)

  // ── Aggregate totals from sessions ────────────────────────────────────────
  const totalTokens = { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }
  let totalCost = 0
  let totalSavings = 0
  const dailyMap = new Map<string, number>()
  const projectMap = new Map<string, { cost: number; input: number; output: number }>()
  const HORS_PROJET = '__hors_projet__'

  for (const s of sessions) {
    const iT  = s.input_tokens ?? 0
    const oT  = s.output_tokens ?? 0
    const crT = s.cache_read_input_tokens ?? 0
    const cwT = s.cache_creation_input_tokens ?? 0

    totalTokens.input      += iT
    totalTokens.output     += oT
    totalTokens.cacheRead  += crT
    totalTokens.cacheWrite += cwT

    const sessionCost =
      iT  * blended.input      +
      oT  * blended.output     +
      crT * blended.cacheRead  +
      cwT * blended.cacheWrite

    // Savings = what cache reads would have cost as input vs. cache-read price.
    const sessionSavings = crT * (blended.input - blended.cacheRead)

    totalCost += sessionCost
    totalSavings += sessionSavings

    // Daily
    const day = (s.start_time ?? '').slice(0, 10)
    if (day) dailyMap.set(day, (dailyMap.get(day) ?? 0) + sessionCost)

    // By project
    const pp = s.project_path ?? ''
    const slug = isAutoGeneratedProject(pp) ? HORS_PROJET : pp
    const existing = projectMap.get(slug) ?? { cost: 0, input: 0, output: 0 }
    projectMap.set(slug, {
      cost: existing.cost + sessionCost,
      input: existing.input + iT,
      output: existing.output + oT,
    })
  }

  const daily: DailyCost[] = [...dailyMap.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([date, total]) => ({ date, costs: { blended: total }, total }))

  // ── Per-model breakdown ──────────────────────────────────────────────────
  // Distribute session token totals to each model using modelUsage per-type
  // ratios, then price each allocation with its real per-model pricing. By
  // construction Σ(model costs) ≈ totalCost (blended weighted mean).
  const usage = stats.modelUsage ?? {}
  const modelTotals = { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }
  for (const u of Object.values(usage)) {
    modelTotals.input      += u.inputTokens ?? 0
    modelTotals.output     += u.outputTokens ?? 0
    modelTotals.cacheRead  += u.cacheReadInputTokens ?? 0
    modelTotals.cacheWrite += u.cacheCreationInputTokens ?? 0
  }

  const models: ModelCostBreakdown[] = Object.entries(usage).map(([model, u]) => {
    const share = {
      input:      modelTotals.input      > 0 ? (u.inputTokens ?? 0)              / modelTotals.input      : 0,
      output:     modelTotals.output     > 0 ? (u.outputTokens ?? 0)             / modelTotals.output     : 0,
      cacheRead:  modelTotals.cacheRead  > 0 ? (u.cacheReadInputTokens ?? 0)     / modelTotals.cacheRead  : 0,
      cacheWrite: modelTotals.cacheWrite > 0 ? (u.cacheCreationInputTokens ?? 0) / modelTotals.cacheWrite : 0,
    }
    const allocated = {
      inputTokens:              totalTokens.input      * share.input,
      outputTokens:             totalTokens.output     * share.output,
      cacheReadInputTokens:     totalTokens.cacheRead  * share.cacheRead,
      cacheCreationInputTokens: totalTokens.cacheWrite * share.cacheWrite,
      costUSD: 0,
      webSearchRequests: 0,
    }
    const cost = estimateTotalCostFromModel(model, allocated)
    const eff = cacheEfficiency(model, allocated)
    return {
      model,
      input_tokens: allocated.inputTokens,
      output_tokens: allocated.outputTokens,
      cache_write_tokens: allocated.cacheCreationInputTokens,
      cache_read_tokens: allocated.cacheReadInputTokens,
      estimated_cost: cost,
      cache_savings: eff.savedUSD ?? 0,
      cache_hit_rate: eff.hitRate ?? 0,
    }
  }).sort((a, b) => b.estimated_cost - a.estimated_cost)

  // ── By project ────────────────────────────────────────────────────────────
  const by_project: ProjectCost[] = [...projectMap.entries()]
    .map(([slug, d]) => {
      const isHP = slug === HORS_PROJET
      return {
        slug: isHP ? 'hors-projet' : slug,
        display_name: isHP ? 'Hors projet' : projectDisplayName(slug),
        estimated_cost: d.cost,
        input_tokens: d.input,
        output_tokens: d.output,
      }
    })
    .sort((a, b) => b.estimated_cost - a.estimated_cost)
    .slice(0, 20)

  const result: CostAnalytics = {
    total_cost: totalCost,
    total_savings: totalSavings,
    models,
    daily,
    by_project,
  }
  return NextResponse.json(result)
}

// Re-export PRICING so the Pricing Reference card can still import it from here
// if needed; the page currently imports it directly from @/lib/pricing.
export { PRICING }
